version: "3"

services:
  api:
    build:
      context: ./app
    command: yarn run start:prod
    env_file:
      - ./app/.env
    ports:
      - "6007"
      - 6006:6006
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 9010:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=spaceship_db

  mongodb:
    image: mongo
    ports:
      - "9011:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "9014:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass REDIS
    volumes:
      - ./.cache:/data

  s3:
    container_name: "${LOCALSTACK_DOCKER_NAME-s3}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d"

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    user: root
    ports:
      - '3200'  # tempo
      - '4317'  # otlp grpc
      - '4318'  # otlp http
    volumes:
      - ./infra/monitoring/tempo.yml:/etc/tempo.yml
      - tempo_data:/tmp/tempo
    command: -config.file=/etc/tempo.yml
    restart: on-failure

  loki:
    container_name: loki
    image: grafana/loki:latest
    user: root
    ports:
      - '3100:3100'
    volumes:
      - ./infra/monitoring/loki.yml:/etc/loki.yml
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki.yml
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    depends_on:
      - "tempo"
      - "prometheus"
    volumes:
      - ./infra/monitoring/otel-collector.yml:/etc/otel-collector.yml
    command:
      - "--config=/etc/otel-collector.yml"
    restart: on-failure


  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./infra/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      # web port
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  grafana_data:
  tempo_data:
  postgres_data:
  mongo_data:
  loki_data:
