version: '3.9'

services:
  api:
    build:
      context: ./spaceship-api
    command: yarn run start:prod
    env_file:
      - ./spaceship-api/.env
    expose:
      - 6006
    ports:
      - 6006:6006
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=spaceship_db
  
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ~/apps/mongo:/var/lib/postgresql/data