apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        ports:
        - containerPort: 1888
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 13133
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
          - name: config
            mountPath: /etc/otel-collector/otel-collector.yml
            subPath: otel-collector.yml
            readOnly: true
        args:
          - "--config=/etc/otel-collector/otel-collector.yml"
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
            items:
              - key: "otel-collector.yml"
                path: "otel-collector.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      name: pprof-port
      port: 1888
      targetPort: 1888
    - protocol: TCP
      name: prom-metric-port
      port: 8888
      targetPort: 8888
    - protocol: TCP
      name: prom-metric-exporter-port
      port: 8889
      targetPort: 8889
    - protocol: TCP
      name: health-check-port
      port: 13133
      targetPort: 13133
    - protocol: TCP
      name: grpc-receiver-port
      port: 4317
      targetPort: 4317
    - protocol: TCP
      name: http-receiver-port
      port: 4318
      targetPort: 4318
  type: LoadBalancer