apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        ports:
        - containerPort: 3200
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: config
          mountPath: /etc/tempo.yml
          subPath: tempo.yml
        args:
        - "-config.file=/etc/tempo.yml"
      volumes:
      - name: config
        configMap:
          name: tempo-config
          items:
            - key: "tempo.yml"
              path: "tempo.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      name: tempo-port
      port: 3200
      targetPort: 3200
    - protocol: TCP
      name: tempo-grpc-port
      port: 4317
      targetPort: 4317
    - protocol: TCP
      name: tempo-http-port
      port: 4318
      targetPort: 4318
  type: LoadBalancer